version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - pip install --upgrade pip
      - pip install mkdocs
  pre_build:
    commands:
#      - cp src/app/services/envs/env-${MATURITY}.ts src/app/services/env.ts
#      - npm install --prod
  build:
    commands:
      - mkdocs build --clean
  post_build:
    commands:
      - cd docs
      - aws s3 sync . "s3://${S3_BUCKET}/asset/docs"
#      - cd ../..
#      - chmod +x ./invalidate-cf.sh
#      - . ./invalidate-cf.sh ${CDN_ID}
