site_name: ASF SAR Data Search Manual
site_description: Documentation for searching and processing ASF SAR data.
site_dir: 'docs'
docs_dir: 'markdown-docs'
google_analytics: ['UA-991100-5', 'search.asf.alaska.edu']

theme:
    name: material
    custom_dir: asf-theme
    favicon: assets/images/favicon.ico
    logo: assets/images/ASFLogo-Blue2.png

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/expert-rec-search.js

copyright: Copyright @ Alaska Satellite Facility

nav:
  - Home: index.md
  - Search UI:
    - Vertex Manual: vertex/manual.md
    - SBAS: vertex/sbas.md
    - Tutorial Videos: https://www.youtube.com/playlist?list=PLXluIEvp5ZzIWd0yNy-ANfdwWjCD1hInA
    - Source Code: https://github.com/asfadmin/Discovery-SearchUI
  - Custom Processing:
    - Hyp3 User Manual: hyp3/manual.md
    - Hyp3 Developer Wiki: https://wiki.asf.alaska.edu/x/WQfdAQ
  - ASF API:
    - API Manual: vertex/manual.md
  - About: about.md
  - ASF Web: 'https://asf.alaska.edu/'
