site_name: ASF SAR Data Search Manual
site_description: Documentation for searching and processing ASF SAR data.
site_dir: 'docs'
docs_dir: 'markdown-docs'
google_analytics: ['UA-991100-5', 'search.asf.alaska.edu']
extra_css:
  - 'css/styles.css'
plugins:
  - mkdocs-video:
      css_style:
        position: "relative"
        width: "50%"
        max-width: "400px"
        min-width: "300px"
        height: "25vw"
        max-height: "250px"
        min-height: "175px"

theme:
    name: asf-theme

copyright: Copyright @ Alaska Satellite Facility

markdown_extensions:
  - toc:
      permalink: "#"
  - attr_list

nav:
  - Home: index.md
  - Vertex:
    - Vertex Manual: vertex/manual.md
    - Baseline: vertex/baseline.md
    - SBAS: vertex/sbas.md
    - Event: vertex/events.md
    - Derived Datasets: vertex/derived_datasets.md
    - What's New: vertex/changelog.md
    - Tutorial Videos: https://www.youtube.com/playlist?list=PLXluIEvp5ZzIWd0yNy-ANfdwWjCD1hInA
    - Source Code: https://github.com/asfadmin/Discovery-SearchUI
  - Custom Processing: https://hyp3-docs.asf.alaska.edu
  - Python Search Module:
    - Basics: asf_search/basics.md
    - Searching: asf_search/searching.md
    - Downloading: asf_search/downloading.md
    - Classes:
      - ASFProduct: asf_search/ASFProduct.md
      - ASFSearchOptions: asf_search/ASFSearchOptions.md
      - ASFSearchResults: asf_search/ASFSearchResults.md
      - ASFSession: asf_search/ASFSession.md
    - Exceptions: asf_search/exceptions.md
    - What's New: https://github.com/asfadmin/Discovery-asf_search/blob/master/CHANGELOG.md
  - ASF Search API:
    - Search API Basics: api/basics.md
    - Search API Keywords & Endpoints: api/keywords.md
    - Tools: api/tools.md
    - Troubleshooting: api/troubleshooting.md
    - Cookbook: api/cookbook.md
    - What's New: api/changelog.md
  # - About: about.md
  - Product Details:
    - Using ASF Data: datasets/using_ASF_data.md
    - ALOS PALSAR Products: datasets/palsar.md
    - Events (SARVIEWS): datasets/events_about.md
  - ASF Web: 'https://asf.alaska.edu/'
