site_name: ASF SAR Data Search Manual
site_description: Documentation for searching and processing ASF SAR data.
site_dir: 'docs'
docs_dir: 'markdown-docs'
google_analytics: ['UA-991100-5', 'search.asf.alaska.edu']

theme:
    name: asf-theme

copyright: Copyright @ Alaska Satellite Facility

nav:
  - Home: index.md
  - Search UI:
    - Vertex Manual: vertex/manual.md
    - Baseline: vertex/baseline.md
    - SBAS: vertex/sbas.md
    - Tutorial Videos: https://www.youtube.com/playlist?list=PLXluIEvp5ZzIWd0yNy-ANfdwWjCD1hInA
    - Source Code: https://github.com/asfadmin/Discovery-SearchUI
  - Custom Processing:
    - Hyp3 User Manual: https://hyp3-docs.asf.alaska.edu
    - Hyp3 Developer Wiki: https://wiki.asf.alaska.edu/x/WQfdAQ
  # - ASF API:
  #   - API Manual: vertex/manual.md
  # - About: about.md
  - ASF Web: 'https://asf.alaska.edu/'
