name: Deploy to Github.io

on:
  push:
    branches:
      - prod

  workflow_dispatch:

jobs:
  build_and_deploy:

    name: Build site and deploy
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          path: asf-data-search-manual

      - name: Setup Python
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs
          python -m pip install mkdocs-material
          python -m pip install mkdocs-asf-theme -U

      - name: deploy to github.io
        if: github.ref == 'refs/heads/prod'
        shell: bash -l {0}
        run: |
          python -m mkdocs gh-deploy  --force --config-file asfadmin/asf-data-search-manual/mkdocs.yml --remote-branch prod
