name: Deploy to Github.io

on:
  push:
    branches:
      - prod

  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build site and deploy
    runs-on: "ubuntu-latest"
    if: github.ref == 'refs/heads/prod'
    steps:
      - uses: actions/checkout@v2
        with:
          repository: asfadmin/asfadmin.github.io
          path: asfadmin.github.io
#          token: ${{ secrets.TOOLS_BOT_PAK }}

      - name: Setup Python
        python -m pip install --upgrade pip
        python -m pip install mkdocs
        python -m pip install mkdocs-asf-theme -U
        pip -m install mkdocs-material

      - name: deploy to github.io
        shell: bash -l {0}
        run: |
          cd asfadmin.github.io
          mkdocs gh-deploy  --force --config-file ../asf-data-search-manual/mkdocs.yml --remote-branch prod
